# Generated by Django 5.2 on 2025-04-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppAdmin',
        ),
    ]
