# Generated by Django 5.2 on 2025-04-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_appadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedcar',
            name='current_step',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
