# Generated by Django 5.2 on 2025-04-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_borrowedcar_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedcar',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('pending', 'Pending')], default='available', max_length=50),
        ),
    ]
