# Generated by Django 5.2 on 2025-04-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_car_image_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('none', 'No Car Borrowed'), ('pending', 'Pending'), ('waiting', 'Waiting Verification'), ('borrowed', 'Borrowed')], default='none', max_length=20),
        ),
    ]
