# Generated by Django 5.2 on 2025-04-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_borrowedcar_current_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
