# Generated by Django 5.2 on 2025-04-23 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.car'),
        ),
    ]
