# Generated by Django 5.2 on 2025-04-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_customuser_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_agreed_terms',
            field=models.BooleanField(default=False),
        ),
    ]
