# Generated by Django 5.2 on 2025-04-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_customuser_has_agreed_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_step',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
