# Generated by Django 5.2 on 2025-04-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_customuser_current_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_step',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
