# Generated by Django 5.2 on 2025-04-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_customuser_current_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_step',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
