# Generated by Django 5.2 on 2025-05-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_customuser_current_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedcar',
            old_name='borrow_date',
            new_name='borrowed_date',
        ),
    ]
