# Generated by Django 5.2 on 2025-05-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_borrow_date_borrowedcar_borrowed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_step',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
