# Generated by Django 5.2 on 2025-05-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_customuser_max_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='max_step',
        ),
    ]
