# Generated by Django 5.2 on 2025-05-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_customuser_max_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='borrowed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
