# Generated by Django 5.2 on 2025-05-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_customuser_borrowed_date_customuser_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('none', 'No Car Borrowed'), ('waiting', 'Waiting Verification'), ('borrowed', 'Borrowed')], default='none', max_length=20),
        ),
    ]
