# Generated by Django 5.2 on 2025-05-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('none', 'No Car Borrowed'), ('pending', 'Waiting Verification'), ('borrowed', 'Borrowed')], default='none', max_length=20),
        ),
    ]
