# Generated by Django 5.2 on 2025-05-16 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_customuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedcar',
            name='borrowed_date',
        ),
        migrations.RemoveField(
            model_name='borrowedcar',
            name='return_date',
        ),
    ]
