# Generated by Django 5.2 on 2025-05-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_borrowcarhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='days_borrowed',
            field=models.IntegerField(default=0),
        ),
    ]
