# Generated by Django 5.2 on 2025-05-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_customuser_days_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowcarhistory',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('pending', 'Pending')], default='ongoing', max_length=20),
        ),
    ]
