# Generated by Django 5.2 on 2025-05-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_borrowcarhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowcarhistory',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('returned', 'Returned')], default='ongoing', max_length=20),
        ),
    ]
